# Generated by Django 2.1.4 on 2019-06-27 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imagepolls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagevote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='imageoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imagepolls.Imagepolldetail'),
        ),
        migrations.AddField(
            model_name='imagevote',
            name='option_vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imagepolls.Imageoption'),
        ),
    ]
