# Generated by Django 2.1.4 on 2019-06-28 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imagepolls', '0002_auto_20190627_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imageoptions', to='imagepolls.Imagepolldetail'),
        ),
    ]
