# Generated by Django 2.1.4 on 2019-06-28 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imagepolls', '0003_auto_20190628_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagevote',
            name='option_vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='imagepolls.Imageoption'),
        ),
    ]
