# Generated by Django 2.1.1 on 2019-08-08 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thinkpollusers', '0002_contact'),
        ('imagepolls', '0004_auto_20190628_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll_cookie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookie_value', models.CharField(max_length=80)),
            ],
        ),
        migrations.AddField(
            model_name='imagepolldetail',
            name='poll_creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='img_poll_creator', to='thinkpollusers.Userdata'),
        ),
        migrations.AddField(
            model_name='poll_cookie',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cookie', to='imagepolls.Imagepolldetail'),
        ),
    ]
