# Generated by Django 2.1.4 on 2019-07-16 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thinkpollusers', '0001_initial'),
        ('poll_detail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='poll_creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='poll_creator', to='thinkpollusers.Userdata'),
        ),
    ]
