# Generated by Django 2.1.1 on 2019-08-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll_detail', '0002_question_poll_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='theme_color',
            field=models.CharField(default='default', max_length=80),
        ),
    ]
