# Generated by Django 2.1.1 on 2019-08-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thinkpollusers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
    ]
